/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecompensasRouteImport } from './routes/_authenticated/recompensas'
import { Route as AuthenticatedGaragemRouteImport } from './routes/_authenticated/garagem'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminResgatesRouteImport } from './routes/_authenticated/admin.resgates'
import { Route as AuthenticatedAdminRecompensasRouteImport } from './routes/_authenticated/admin.recompensas'
import { Route as AuthenticatedAdminCarrosRouteImport } from './routes/_authenticated/admin.carros'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecompensasRoute =
  AuthenticatedRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaragemRoute = AuthenticatedGaragemRouteImport.update({
  id: '/garagem',
  path: '/garagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminResgatesRoute =
  AuthenticatedAdminResgatesRouteImport.update({
    id: '/resgates',
    path: '/resgates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecompensasRoute =
  AuthenticatedAdminRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCarrosRoute =
  AuthenticatedAdminCarrosRouteImport.update({
    id: '/carros',
    path: '/carros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/garagem': typeof AuthenticatedGaragemRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/admin/carros': typeof AuthenticatedAdminCarrosRoute
  '/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/admin/resgates': typeof AuthenticatedAdminResgatesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/garagem': typeof AuthenticatedGaragemRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/admin/carros': typeof AuthenticatedAdminCarrosRoute
  '/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/admin/resgates': typeof AuthenticatedAdminResgatesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/garagem': typeof AuthenticatedGaragemRoute
  '/_authenticated/recompensas': typeof AuthenticatedRecompensasRoute
  '/_authenticated/admin/carros': typeof AuthenticatedAdminCarrosRoute
  '/_authenticated/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/_authenticated/admin/resgates': typeof AuthenticatedAdminResgatesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/garagem'
    | '/recompensas'
    | '/admin/carros'
    | '/admin/recompensas'
    | '/admin/resgates'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/garagem'
    | '/recompensas'
    | '/admin/carros'
    | '/admin/recompensas'
    | '/admin/resgates'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/garagem'
    | '/_authenticated/recompensas'
    | '/_authenticated/admin/carros'
    | '/_authenticated/admin/recompensas'
    | '/_authenticated/admin/resgates'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recompensas': {
      id: '/_authenticated/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof AuthenticatedRecompensasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garagem': {
      id: '/_authenticated/garagem'
      path: '/garagem'
      fullPath: '/garagem'
      preLoaderRoute: typeof AuthenticatedGaragemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resgates': {
      id: '/_authenticated/admin/resgates'
      path: '/resgates'
      fullPath: '/admin/resgates'
      preLoaderRoute: typeof AuthenticatedAdminResgatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recompensas': {
      id: '/_authenticated/admin/recompensas'
      path: '/recompensas'
      fullPath: '/admin/recompensas'
      preLoaderRoute: typeof AuthenticatedAdminRecompensasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/carros': {
      id: '/_authenticated/admin/carros'
      path: '/carros'
      fullPath: '/admin/carros'
      preLoaderRoute: typeof AuthenticatedAdminCarrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCarrosRoute: typeof AuthenticatedAdminCarrosRoute
  AuthenticatedAdminRecompensasRoute: typeof AuthenticatedAdminRecompensasRoute
  AuthenticatedAdminResgatesRoute: typeof AuthenticatedAdminResgatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCarrosRoute: AuthenticatedAdminCarrosRoute,
  AuthenticatedAdminRecompensasRoute: AuthenticatedAdminRecompensasRoute,
  AuthenticatedAdminResgatesRoute: AuthenticatedAdminResgatesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedGaragemRoute: typeof AuthenticatedGaragemRoute
  AuthenticatedRecompensasRoute: typeof AuthenticatedRecompensasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedGaragemRoute: AuthenticatedGaragemRoute,
  AuthenticatedRecompensasRoute: AuthenticatedRecompensasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
