/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as CreateStoreRouteImport } from './routes/create-store'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StoreSlugRouteImport } from './routes/$storeSlug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugIndexRouteImport } from './routes/$storeSlug.index'
import { Route as AuthenticatedRifasRouteImport } from './routes/_authenticated/rifas'
import { Route as AuthenticatedRecompensasRouteImport } from './routes/_authenticated/recompensas'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedGaragemRouteImport } from './routes/_authenticated/garagem'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as StoreSlugLoginRouteImport } from './routes/$storeSlug.login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminRifasRouteImport } from './routes/_authenticated/admin.rifas'
import { Route as AuthenticatedAdminResgatesRouteImport } from './routes/_authenticated/admin.resgates'
import { Route as AuthenticatedAdminRecompensasRouteImport } from './routes/_authenticated/admin.recompensas'
import { Route as AuthenticatedAdminGaragensRouteImport } from './routes/_authenticated/admin.garagens'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin.estoque'
import { Route as AuthenticatedAdminCarrosRouteImport } from './routes/_authenticated/admin.carros'

const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateStoreRoute = CreateStoreRouteImport.update({
  id: '/create-store',
  path: '/create-store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/$storeSlug',
  path: '/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugIndexRoute = StoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreSlugRoute,
} as any)
const AuthenticatedRifasRoute = AuthenticatedRifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecompensasRoute =
  AuthenticatedRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaragemRoute = AuthenticatedGaragemRouteImport.update({
  id: '/garagem',
  path: '/garagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StoreSlugLoginRoute = StoreSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StoreSlugRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRifasRoute = AuthenticatedAdminRifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminResgatesRoute =
  AuthenticatedAdminResgatesRouteImport.update({
    id: '/resgates',
    path: '/resgates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecompensasRoute =
  AuthenticatedAdminRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGaragensRoute =
  AuthenticatedAdminGaragensRouteImport.update({
    id: '/garagens',
    path: '/garagens',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCarrosRoute =
  AuthenticatedAdminCarrosRouteImport.update({
    id: '/carros',
    path: '/carros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$storeSlug': typeof StoreSlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/create-store': typeof CreateStoreRoute
  '/saas': typeof SaasRoute
  '/$storeSlug/login': typeof StoreSlugLoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/garagem': typeof AuthenticatedGaragemRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/rifas': typeof AuthenticatedRifasRoute
  '/$storeSlug/': typeof StoreSlugIndexRoute
  '/admin/carros': typeof AuthenticatedAdminCarrosRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/garagens': typeof AuthenticatedAdminGaragensRoute
  '/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/admin/resgates': typeof AuthenticatedAdminResgatesRoute
  '/admin/rifas': typeof AuthenticatedAdminRifasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-store': typeof CreateStoreRoute
  '/saas': typeof SaasRoute
  '/$storeSlug/login': typeof StoreSlugLoginRoute
  '/garagem': typeof AuthenticatedGaragemRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/rifas': typeof AuthenticatedRifasRoute
  '/$storeSlug': typeof StoreSlugIndexRoute
  '/admin/carros': typeof AuthenticatedAdminCarrosRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/garagens': typeof AuthenticatedAdminGaragensRoute
  '/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/admin/resgates': typeof AuthenticatedAdminResgatesRoute
  '/admin/rifas': typeof AuthenticatedAdminRifasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$storeSlug': typeof StoreSlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/create-store': typeof CreateStoreRoute
  '/saas': typeof SaasRoute
  '/$storeSlug/login': typeof StoreSlugLoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/garagem': typeof AuthenticatedGaragemRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/recompensas': typeof AuthenticatedRecompensasRoute
  '/_authenticated/rifas': typeof AuthenticatedRifasRoute
  '/$storeSlug/': typeof StoreSlugIndexRoute
  '/_authenticated/admin/carros': typeof AuthenticatedAdminCarrosRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/garagens': typeof AuthenticatedAdminGaragensRoute
  '/_authenticated/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/_authenticated/admin/resgates': typeof AuthenticatedAdminResgatesRoute
  '/_authenticated/admin/rifas': typeof AuthenticatedAdminRifasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$storeSlug'
    | '/auth'
    | '/create-store'
    | '/saas'
    | '/$storeSlug/login'
    | '/admin'
    | '/garagem'
    | '/loja'
    | '/ranking'
    | '/recompensas'
    | '/rifas'
    | '/$storeSlug/'
    | '/admin/carros'
    | '/admin/estoque'
    | '/admin/garagens'
    | '/admin/recompensas'
    | '/admin/resgates'
    | '/admin/rifas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-store'
    | '/saas'
    | '/$storeSlug/login'
    | '/garagem'
    | '/loja'
    | '/ranking'
    | '/recompensas'
    | '/rifas'
    | '/$storeSlug'
    | '/admin/carros'
    | '/admin/estoque'
    | '/admin/garagens'
    | '/admin/recompensas'
    | '/admin/resgates'
    | '/admin/rifas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$storeSlug'
    | '/auth'
    | '/create-store'
    | '/saas'
    | '/$storeSlug/login'
    | '/_authenticated/admin'
    | '/_authenticated/garagem'
    | '/_authenticated/loja'
    | '/_authenticated/ranking'
    | '/_authenticated/recompensas'
    | '/_authenticated/rifas'
    | '/$storeSlug/'
    | '/_authenticated/admin/carros'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/garagens'
    | '/_authenticated/admin/recompensas'
    | '/_authenticated/admin/resgates'
    | '/_authenticated/admin/rifas'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  StoreSlugRoute: typeof StoreSlugRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreateStoreRoute: typeof CreateStoreRoute
  SaasRoute: typeof SaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-store': {
      id: '/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof CreateStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug': {
      id: '/$storeSlug'
      path: '/$storeSlug'
      fullPath: '/$storeSlug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$storeSlug/': {
      id: '/$storeSlug/'
      path: '/'
      fullPath: '/$storeSlug/'
      preLoaderRoute: typeof StoreSlugIndexRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/_authenticated/rifas': {
      id: '/_authenticated/rifas'
      path: '/rifas'
      fullPath: '/rifas'
      preLoaderRoute: typeof AuthenticatedRifasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recompensas': {
      id: '/_authenticated/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof AuthenticatedRecompensasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garagem': {
      id: '/_authenticated/garagem'
      path: '/garagem'
      fullPath: '/garagem'
      preLoaderRoute: typeof AuthenticatedGaragemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$storeSlug/login': {
      id: '/$storeSlug/login'
      path: '/login'
      fullPath: '/$storeSlug/login'
      preLoaderRoute: typeof StoreSlugLoginRouteImport
      parentRoute: typeof StoreSlugRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rifas': {
      id: '/_authenticated/admin/rifas'
      path: '/rifas'
      fullPath: '/admin/rifas'
      preLoaderRoute: typeof AuthenticatedAdminRifasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resgates': {
      id: '/_authenticated/admin/resgates'
      path: '/resgates'
      fullPath: '/admin/resgates'
      preLoaderRoute: typeof AuthenticatedAdminResgatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recompensas': {
      id: '/_authenticated/admin/recompensas'
      path: '/recompensas'
      fullPath: '/admin/recompensas'
      preLoaderRoute: typeof AuthenticatedAdminRecompensasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/garagens': {
      id: '/_authenticated/admin/garagens'
      path: '/garagens'
      fullPath: '/admin/garagens'
      preLoaderRoute: typeof AuthenticatedAdminGaragensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/carros': {
      id: '/_authenticated/admin/carros'
      path: '/carros'
      fullPath: '/admin/carros'
      preLoaderRoute: typeof AuthenticatedAdminCarrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCarrosRoute: typeof AuthenticatedAdminCarrosRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminGaragensRoute: typeof AuthenticatedAdminGaragensRoute
  AuthenticatedAdminRecompensasRoute: typeof AuthenticatedAdminRecompensasRoute
  AuthenticatedAdminResgatesRoute: typeof AuthenticatedAdminResgatesRoute
  AuthenticatedAdminRifasRoute: typeof AuthenticatedAdminRifasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCarrosRoute: AuthenticatedAdminCarrosRoute,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminGaragensRoute: AuthenticatedAdminGaragensRoute,
  AuthenticatedAdminRecompensasRoute: AuthenticatedAdminRecompensasRoute,
  AuthenticatedAdminResgatesRoute: AuthenticatedAdminResgatesRoute,
  AuthenticatedAdminRifasRoute: AuthenticatedAdminRifasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedGaragemRoute: typeof AuthenticatedGaragemRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRecompensasRoute: typeof AuthenticatedRecompensasRoute
  AuthenticatedRifasRoute: typeof AuthenticatedRifasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedGaragemRoute: AuthenticatedGaragemRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRecompensasRoute: AuthenticatedRecompensasRoute,
  AuthenticatedRifasRoute: AuthenticatedRifasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StoreSlugRouteChildren {
  StoreSlugLoginRoute: typeof StoreSlugLoginRoute
  StoreSlugIndexRoute: typeof StoreSlugIndexRoute
}

const StoreSlugRouteChildren: StoreSlugRouteChildren = {
  StoreSlugLoginRoute: StoreSlugLoginRoute,
  StoreSlugIndexRoute: StoreSlugIndexRoute,
}

const StoreSlugRouteWithChildren = StoreSlugRoute._addFileChildren(
  StoreSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  StoreSlugRoute: StoreSlugRouteWithChildren,
  AuthRoute: AuthRoute,
  CreateStoreRoute: CreateStoreRoute,
  SaasRoute: SaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
